spring:
  application:
    name: nexus
  datasource:
    url: jdbc:h2:tcp://localhost/~/cheerlas-nexus
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: admin
      password: admin
